using DevExpress.XtraEditors;
using Library_MVP.Logic.Presenter;
using Library_MVP.Views.Interface;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;

namespace Library_MVP.Views.Pages
{
    public partial class Control_BookPlace : DevExpress.XtraEditors.XtraUserControl , IBookPlace
    {
        BookPlacePresenter bookPlacePresenter;
        public Control_BookPlace()
        {
            InitializeComponent();
            LoadData();
            bookPlacePresenter = new BookPlacePresenter(this);
        }

        #region Implement Interface
        public int Id { get => Convert.ToInt32(txbIDBookPlace.Text.Trim()); set => txbIDBookPlace.Text = value.ToString(); }
        public string BookPlaceName { get => txbNameBookPlace.Text.Trim(); set => txbNameBookPlace.Text = value; }
        object IBookPlace.txbNameBookPlace { get => txbNameBookPlace.Focus(); set => txbNameBookPlace.Focus(); }
        bool IBookPlace.btnAdd { get => btnAdd.Enabled; set => btnAdd.Enabled = value; }
        bool IBookPlace.btnModifier { get => btnModifier.Enabled; set => btnModifier.Enabled = value; }
        public bool btnRemove { get => btnSuprimer.Enabled; set => btnSuprimer.Enabled = value; }
        public bool btnRemoveAll { get => btnSuprimerAll.Enabled; set => btnSuprimerAll.Enabled = value; }
        #endregion

        #region Events
        private void Control_BookPlace_Load(object sender, EventArgs e)
        {
            bookPlacePresenter.AutoNumber();
        }
        private void btnAdd_Click(object sender, EventArgs e)
        {
            bool check = bookPlacePresenter.BookPlaceInsert();
            if (check)
            {
                toastNotificationsManager1.ShowNotification("3781fe64-5293-41c7-868f-d2f838e0dd43");
                LoadData();
            }
            else
            {
                toastNotificationsManager1.ShowNotification("e17aa1d8-200a-4ca1-b503-1a631220eea9");
            }
        }
        private void btnModifier_Click(object sender, EventArgs e)
        {
            bool check = bookPlacePresenter.BookPlaceUpdate();
            if (check)
            {
                toastNotificationsManager1.ShowNotification("3781fe64-5293-41c7-868f-d2f838e0dd43");
                LoadData();
            }
            else
            {
                toastNotificationsManager1.ShowNotification("e17aa1d8-200a-4ca1-b503-1a631220eea9");
            }
        }
        private void btnSuprimer_Click(object sender, EventArgs e)
        {
            bool check = bookPlacePresenter.BookPlaceDelete();
            if (check)
            {
                toastNotificationsManager1.ShowNotification("3781fe64-5293-41c7-868f-d2f838e0dd43");
                LoadData();
            }
            else
            {
                toastNotificationsManager1.ShowNotification("e17aa1d8-200a-4ca1-b503-1a631220eea9");
            }
        }
        private void btnSuprimerAll_Click(object sender, EventArgs e)
        {
            bool check = bookPlacePresenter.BookPlaceDeleteAll();
            if (check)
            {
                toastNotificationsManager1.ShowNotification("3781fe64-5293-41c7-868f-d2f838e0dd43");
                LoadData();
            }
            else
            {
                toastNotificationsManager1.ShowNotification("e17aa1d8-200a-4ca1-b503-1a631220eea9");
            }
        }
        private void btnRefriche_Click(object sender, EventArgs e)
        {
            bookPlacePresenter.AutoNumber();
        }
        private void btnPrint_Click(object sender, EventArgs e)
        {
            gridControlBookPlace.ShowPrintPreview();
        }
        private void gridControl1_DoubleClick(object sender, EventArgs e)
        {
            try
            {
                if (bookPlacePresenter.getCountAllRow() != 0)
                {
                    txbIDBookPlace.Text = gridViewBookPlace.GetFocusedRowCellValue("رقم المكان").ToString();
                    txbNameBookPlace.Text = gridViewBookPlace.GetFocusedRowCellValue("اسم المكان").ToString();
                    bookPlacePresenter.UpdateRomoveButtons();
                }
            }
            catch (Exception) { }
        }
        #endregion

        #region Function Load DataBase
        private void LoadData()
        {
            // This line of code is generated by Data Source Configuration Wizard
            // Fill the SqlDataSource asynchronously
            sqlDataSource1.FillAsync();
        }

        #endregion
    }
}
